# Generated by Django 4.2.16 on 2024-09-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bets", "0002_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dispute",
        ),
    ]
