# Generated by Django 4.2.16 on 2024-09-26 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bets", "0003_delete_dispute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="content",
        ),
        migrations.AddField(
            model_name="notification",
            name="bet",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="bets.bet"
            ),
            preserve_default=False,
        ),
    ]
