# Generated by Django 4.2.16 on 2024-09-26 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bets", "0004_remove_notification_content_notification_bet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="user",
            new_name="user_to",
        ),
    ]
