# Generated by Django 4.2.16 on 2024-09-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bets", "0006_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
