# Generated by Django 4.2.16 on 2024-09-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bets", "0007_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwallet",
            name="on_hold_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
