# Generated by Django 4.2.16 on 2024-09-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bets", "0008_userwallet_on_hold_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
